#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorksDW2014")]
	public partial class AdventureWorksDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDimProduct(DimProduct instance);
    partial void UpdateDimProduct(DimProduct instance);
    partial void DeleteDimProduct(DimProduct instance);
    partial void InsertDimProductCategory(DimProductCategory instance);
    partial void UpdateDimProductCategory(DimProductCategory instance);
    partial void DeleteDimProductCategory(DimProductCategory instance);
    partial void InsertDimProductSubcategory(DimProductSubcategory instance);
    partial void UpdateDimProductSubcategory(DimProductSubcategory instance);
    partial void DeleteDimProductSubcategory(DimProductSubcategory instance);
    #endregion
		
		public AdventureWorksDataContext() : 
				base(global::LinqToSql.Properties.Settings.Default.AdventureWorksDW2014ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdventureWorksDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdventureWorksDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdventureWorksDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdventureWorksDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DimProduct> DimProducts
		{
			get
			{
				return this.GetTable<DimProduct>();
			}
		}
		
		public System.Data.Linq.Table<DimProductCategory> DimProductCategories
		{
			get
			{
				return this.GetTable<DimProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<DimProductSubcategory> DimProductSubcategories
		{
			get
			{
				return this.GetTable<DimProductSubcategory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimProduct")]
	public partial class DimProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductKey;
		
		private string _ProductAlternateKey;
		
		private System.Nullable<int> _ProductSubcategoryKey;
		
		private string _WeightUnitMeasureCode;
		
		private string _SizeUnitMeasureCode;
		
		private string _EnglishProductName;
		
		private string _SpanishProductName;
		
		private string _FrenchProductName;
		
		private System.Nullable<decimal> _StandardCost;
		
		private bool _FinishedGoodsFlag;
		
		private string _Color;
		
		private System.Nullable<short> _SafetyStockLevel;
		
		private System.Nullable<short> _ReorderPoint;
		
		private System.Nullable<decimal> _ListPrice;
		
		private string _Size;
		
		private string _SizeRange;
		
		private System.Nullable<double> _Weight;
		
		private System.Nullable<int> _DaysToManufacture;
		
		private string _ProductLine;
		
		private System.Nullable<decimal> _DealerPrice;
		
		private string _Class;
		
		private string _Style;
		
		private string _ModelName;
		
		private System.Data.Linq.Binary _LargePhoto;
		
		private string _EnglishDescription;
		
		private string _FrenchDescription;
		
		private string _ChineseDescription;
		
		private string _ArabicDescription;
		
		private string _HebrewDescription;
		
		private string _ThaiDescription;
		
		private string _GermanDescription;
		
		private string _JapaneseDescription;
		
		private string _TurkishDescription;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private string _Status;
		
		private EntityRef<DimProductSubcategory> _DimProductSubcategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductKeyChanging(int value);
    partial void OnProductKeyChanged();
    partial void OnProductAlternateKeyChanging(string value);
    partial void OnProductAlternateKeyChanged();
    partial void OnProductSubcategoryKeyChanging(System.Nullable<int> value);
    partial void OnProductSubcategoryKeyChanged();
    partial void OnWeightUnitMeasureCodeChanging(string value);
    partial void OnWeightUnitMeasureCodeChanged();
    partial void OnSizeUnitMeasureCodeChanging(string value);
    partial void OnSizeUnitMeasureCodeChanged();
    partial void OnEnglishProductNameChanging(string value);
    partial void OnEnglishProductNameChanged();
    partial void OnSpanishProductNameChanging(string value);
    partial void OnSpanishProductNameChanged();
    partial void OnFrenchProductNameChanging(string value);
    partial void OnFrenchProductNameChanged();
    partial void OnStandardCostChanging(System.Nullable<decimal> value);
    partial void OnStandardCostChanged();
    partial void OnFinishedGoodsFlagChanging(bool value);
    partial void OnFinishedGoodsFlagChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnSafetyStockLevelChanging(System.Nullable<short> value);
    partial void OnSafetyStockLevelChanged();
    partial void OnReorderPointChanging(System.Nullable<short> value);
    partial void OnReorderPointChanged();
    partial void OnListPriceChanging(System.Nullable<decimal> value);
    partial void OnListPriceChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnSizeRangeChanging(string value);
    partial void OnSizeRangeChanged();
    partial void OnWeightChanging(System.Nullable<double> value);
    partial void OnWeightChanged();
    partial void OnDaysToManufactureChanging(System.Nullable<int> value);
    partial void OnDaysToManufactureChanged();
    partial void OnProductLineChanging(string value);
    partial void OnProductLineChanged();
    partial void OnDealerPriceChanging(System.Nullable<decimal> value);
    partial void OnDealerPriceChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    partial void OnStyleChanging(string value);
    partial void OnStyleChanged();
    partial void OnModelNameChanging(string value);
    partial void OnModelNameChanged();
    partial void OnLargePhotoChanging(System.Data.Linq.Binary value);
    partial void OnLargePhotoChanged();
    partial void OnEnglishDescriptionChanging(string value);
    partial void OnEnglishDescriptionChanged();
    partial void OnFrenchDescriptionChanging(string value);
    partial void OnFrenchDescriptionChanged();
    partial void OnChineseDescriptionChanging(string value);
    partial void OnChineseDescriptionChanged();
    partial void OnArabicDescriptionChanging(string value);
    partial void OnArabicDescriptionChanged();
    partial void OnHebrewDescriptionChanging(string value);
    partial void OnHebrewDescriptionChanged();
    partial void OnThaiDescriptionChanging(string value);
    partial void OnThaiDescriptionChanged();
    partial void OnGermanDescriptionChanging(string value);
    partial void OnGermanDescriptionChanged();
    partial void OnJapaneseDescriptionChanging(string value);
    partial void OnJapaneseDescriptionChanged();
    partial void OnTurkishDescriptionChanging(string value);
    partial void OnTurkishDescriptionChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public DimProduct()
		{
			this._DimProductSubcategory = default(EntityRef<DimProductSubcategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductKey
		{
			get
			{
				return this._ProductKey;
			}
			set
			{
				if ((this._ProductKey != value))
				{
					this.OnProductKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductKey = value;
					this.SendPropertyChanged("ProductKey");
					this.OnProductKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductAlternateKey", DbType="NVarChar(25)")]
		public string ProductAlternateKey
		{
			get
			{
				return this._ProductAlternateKey;
			}
			set
			{
				if ((this._ProductAlternateKey != value))
				{
					this.OnProductAlternateKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductAlternateKey = value;
					this.SendPropertyChanged("ProductAlternateKey");
					this.OnProductAlternateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSubcategoryKey", DbType="Int")]
		public System.Nullable<int> ProductSubcategoryKey
		{
			get
			{
				return this._ProductSubcategoryKey;
			}
			set
			{
				if ((this._ProductSubcategoryKey != value))
				{
					if (this._DimProductSubcategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductSubcategoryKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductSubcategoryKey = value;
					this.SendPropertyChanged("ProductSubcategoryKey");
					this.OnProductSubcategoryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightUnitMeasureCode", DbType="NChar(3)")]
		public string WeightUnitMeasureCode
		{
			get
			{
				return this._WeightUnitMeasureCode;
			}
			set
			{
				if ((this._WeightUnitMeasureCode != value))
				{
					this.OnWeightUnitMeasureCodeChanging(value);
					this.SendPropertyChanging();
					this._WeightUnitMeasureCode = value;
					this.SendPropertyChanged("WeightUnitMeasureCode");
					this.OnWeightUnitMeasureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeUnitMeasureCode", DbType="NChar(3)")]
		public string SizeUnitMeasureCode
		{
			get
			{
				return this._SizeUnitMeasureCode;
			}
			set
			{
				if ((this._SizeUnitMeasureCode != value))
				{
					this.OnSizeUnitMeasureCodeChanging(value);
					this.SendPropertyChanging();
					this._SizeUnitMeasureCode = value;
					this.SendPropertyChanged("SizeUnitMeasureCode");
					this.OnSizeUnitMeasureCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnglishProductName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EnglishProductName
		{
			get
			{
				return this._EnglishProductName;
			}
			set
			{
				if ((this._EnglishProductName != value))
				{
					this.OnEnglishProductNameChanging(value);
					this.SendPropertyChanging();
					this._EnglishProductName = value;
					this.SendPropertyChanged("EnglishProductName");
					this.OnEnglishProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpanishProductName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SpanishProductName
		{
			get
			{
				return this._SpanishProductName;
			}
			set
			{
				if ((this._SpanishProductName != value))
				{
					this.OnSpanishProductNameChanging(value);
					this.SendPropertyChanging();
					this._SpanishProductName = value;
					this.SendPropertyChanged("SpanishProductName");
					this.OnSpanishProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrenchProductName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FrenchProductName
		{
			get
			{
				return this._FrenchProductName;
			}
			set
			{
				if ((this._FrenchProductName != value))
				{
					this.OnFrenchProductNameChanging(value);
					this.SendPropertyChanging();
					this._FrenchProductName = value;
					this.SendPropertyChanged("FrenchProductName");
					this.OnFrenchProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardCost", DbType="Money")]
		public System.Nullable<decimal> StandardCost
		{
			get
			{
				return this._StandardCost;
			}
			set
			{
				if ((this._StandardCost != value))
				{
					this.OnStandardCostChanging(value);
					this.SendPropertyChanging();
					this._StandardCost = value;
					this.SendPropertyChanged("StandardCost");
					this.OnStandardCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedGoodsFlag", DbType="Bit NOT NULL")]
		public bool FinishedGoodsFlag
		{
			get
			{
				return this._FinishedGoodsFlag;
			}
			set
			{
				if ((this._FinishedGoodsFlag != value))
				{
					this.OnFinishedGoodsFlagChanging(value);
					this.SendPropertyChanging();
					this._FinishedGoodsFlag = value;
					this.SendPropertyChanged("FinishedGoodsFlag");
					this.OnFinishedGoodsFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SafetyStockLevel", DbType="SmallInt")]
		public System.Nullable<short> SafetyStockLevel
		{
			get
			{
				return this._SafetyStockLevel;
			}
			set
			{
				if ((this._SafetyStockLevel != value))
				{
					this.OnSafetyStockLevelChanging(value);
					this.SendPropertyChanging();
					this._SafetyStockLevel = value;
					this.SendPropertyChanged("SafetyStockLevel");
					this.OnSafetyStockLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReorderPoint", DbType="SmallInt")]
		public System.Nullable<short> ReorderPoint
		{
			get
			{
				return this._ReorderPoint;
			}
			set
			{
				if ((this._ReorderPoint != value))
				{
					this.OnReorderPointChanging(value);
					this.SendPropertyChanging();
					this._ReorderPoint = value;
					this.SendPropertyChanged("ReorderPoint");
					this.OnReorderPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListPrice", DbType="Money")]
		public System.Nullable<decimal> ListPrice
		{
			get
			{
				return this._ListPrice;
			}
			set
			{
				if ((this._ListPrice != value))
				{
					this.OnListPriceChanging(value);
					this.SendPropertyChanging();
					this._ListPrice = value;
					this.SendPropertyChanged("ListPrice");
					this.OnListPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(50)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeRange", DbType="NVarChar(50)")]
		public string SizeRange
		{
			get
			{
				return this._SizeRange;
			}
			set
			{
				if ((this._SizeRange != value))
				{
					this.OnSizeRangeChanging(value);
					this.SendPropertyChanging();
					this._SizeRange = value;
					this.SendPropertyChanged("SizeRange");
					this.OnSizeRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysToManufacture", DbType="Int")]
		public System.Nullable<int> DaysToManufacture
		{
			get
			{
				return this._DaysToManufacture;
			}
			set
			{
				if ((this._DaysToManufacture != value))
				{
					this.OnDaysToManufactureChanging(value);
					this.SendPropertyChanging();
					this._DaysToManufacture = value;
					this.SendPropertyChanged("DaysToManufacture");
					this.OnDaysToManufactureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductLine", DbType="NChar(2)")]
		public string ProductLine
		{
			get
			{
				return this._ProductLine;
			}
			set
			{
				if ((this._ProductLine != value))
				{
					this.OnProductLineChanging(value);
					this.SendPropertyChanging();
					this._ProductLine = value;
					this.SendPropertyChanged("ProductLine");
					this.OnProductLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerPrice", DbType="Money")]
		public System.Nullable<decimal> DealerPrice
		{
			get
			{
				return this._DealerPrice;
			}
			set
			{
				if ((this._DealerPrice != value))
				{
					this.OnDealerPriceChanging(value);
					this.SendPropertyChanging();
					this._DealerPrice = value;
					this.SendPropertyChanged("DealerPrice");
					this.OnDealerPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NChar(2)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style", DbType="NChar(2)")]
		public string Style
		{
			get
			{
				return this._Style;
			}
			set
			{
				if ((this._Style != value))
				{
					this.OnStyleChanging(value);
					this.SendPropertyChanging();
					this._Style = value;
					this.SendPropertyChanged("Style");
					this.OnStyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(50)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this.OnModelNameChanging(value);
					this.SendPropertyChanging();
					this._ModelName = value;
					this.SendPropertyChanged("ModelName");
					this.OnModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePhoto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LargePhoto
		{
			get
			{
				return this._LargePhoto;
			}
			set
			{
				if ((this._LargePhoto != value))
				{
					this.OnLargePhotoChanging(value);
					this.SendPropertyChanging();
					this._LargePhoto = value;
					this.SendPropertyChanged("LargePhoto");
					this.OnLargePhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnglishDescription", DbType="NVarChar(400)")]
		public string EnglishDescription
		{
			get
			{
				return this._EnglishDescription;
			}
			set
			{
				if ((this._EnglishDescription != value))
				{
					this.OnEnglishDescriptionChanging(value);
					this.SendPropertyChanging();
					this._EnglishDescription = value;
					this.SendPropertyChanged("EnglishDescription");
					this.OnEnglishDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrenchDescription", DbType="NVarChar(400)")]
		public string FrenchDescription
		{
			get
			{
				return this._FrenchDescription;
			}
			set
			{
				if ((this._FrenchDescription != value))
				{
					this.OnFrenchDescriptionChanging(value);
					this.SendPropertyChanging();
					this._FrenchDescription = value;
					this.SendPropertyChanged("FrenchDescription");
					this.OnFrenchDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChineseDescription", DbType="NVarChar(400)")]
		public string ChineseDescription
		{
			get
			{
				return this._ChineseDescription;
			}
			set
			{
				if ((this._ChineseDescription != value))
				{
					this.OnChineseDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ChineseDescription = value;
					this.SendPropertyChanged("ChineseDescription");
					this.OnChineseDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArabicDescription", DbType="NVarChar(400)")]
		public string ArabicDescription
		{
			get
			{
				return this._ArabicDescription;
			}
			set
			{
				if ((this._ArabicDescription != value))
				{
					this.OnArabicDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ArabicDescription = value;
					this.SendPropertyChanged("ArabicDescription");
					this.OnArabicDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HebrewDescription", DbType="NVarChar(400)")]
		public string HebrewDescription
		{
			get
			{
				return this._HebrewDescription;
			}
			set
			{
				if ((this._HebrewDescription != value))
				{
					this.OnHebrewDescriptionChanging(value);
					this.SendPropertyChanging();
					this._HebrewDescription = value;
					this.SendPropertyChanged("HebrewDescription");
					this.OnHebrewDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThaiDescription", DbType="NVarChar(400)")]
		public string ThaiDescription
		{
			get
			{
				return this._ThaiDescription;
			}
			set
			{
				if ((this._ThaiDescription != value))
				{
					this.OnThaiDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ThaiDescription = value;
					this.SendPropertyChanged("ThaiDescription");
					this.OnThaiDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GermanDescription", DbType="NVarChar(400)")]
		public string GermanDescription
		{
			get
			{
				return this._GermanDescription;
			}
			set
			{
				if ((this._GermanDescription != value))
				{
					this.OnGermanDescriptionChanging(value);
					this.SendPropertyChanging();
					this._GermanDescription = value;
					this.SendPropertyChanged("GermanDescription");
					this.OnGermanDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JapaneseDescription", DbType="NVarChar(400)")]
		public string JapaneseDescription
		{
			get
			{
				return this._JapaneseDescription;
			}
			set
			{
				if ((this._JapaneseDescription != value))
				{
					this.OnJapaneseDescriptionChanging(value);
					this.SendPropertyChanging();
					this._JapaneseDescription = value;
					this.SendPropertyChanged("JapaneseDescription");
					this.OnJapaneseDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurkishDescription", DbType="NVarChar(400)")]
		public string TurkishDescription
		{
			get
			{
				return this._TurkishDescription;
			}
			set
			{
				if ((this._TurkishDescription != value))
				{
					this.OnTurkishDescriptionChanging(value);
					this.SendPropertyChanging();
					this._TurkishDescription = value;
					this.SendPropertyChanged("TurkishDescription");
					this.OnTurkishDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(7)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DimProductSubcategory_DimProduct", Storage="_DimProductSubcategory", ThisKey="ProductSubcategoryKey", OtherKey="ProductSubcategoryKey", IsForeignKey=true)]
		public DimProductSubcategory DimProductSubcategory
		{
			get
			{
				return this._DimProductSubcategory.Entity;
			}
			set
			{
				DimProductSubcategory previousValue = this._DimProductSubcategory.Entity;
				if (((previousValue != value) 
							|| (this._DimProductSubcategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DimProductSubcategory.Entity = null;
						previousValue.DimProducts.Remove(this);
					}
					this._DimProductSubcategory.Entity = value;
					if ((value != null))
					{
						value.DimProducts.Add(this);
						this._ProductSubcategoryKey = value.ProductSubcategoryKey;
					}
					else
					{
						this._ProductSubcategoryKey = default(Nullable<int>);
					}
					this.SendPropertyChanged("DimProductSubcategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimProductCategory")]
	public partial class DimProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductCategoryKey;
		
		private System.Nullable<int> _ProductCategoryAlternateKey;
		
		private string _EnglishProductCategoryName;
		
		private string _SpanishProductCategoryName;
		
		private string _FrenchProductCategoryName;
		
		private EntitySet<DimProductSubcategory> _DimProductSubcategories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductCategoryKeyChanging(int value);
    partial void OnProductCategoryKeyChanged();
    partial void OnProductCategoryAlternateKeyChanging(System.Nullable<int> value);
    partial void OnProductCategoryAlternateKeyChanged();
    partial void OnEnglishProductCategoryNameChanging(string value);
    partial void OnEnglishProductCategoryNameChanged();
    partial void OnSpanishProductCategoryNameChanging(string value);
    partial void OnSpanishProductCategoryNameChanged();
    partial void OnFrenchProductCategoryNameChanging(string value);
    partial void OnFrenchProductCategoryNameChanged();
    #endregion
		
		public DimProductCategory()
		{
			this._DimProductSubcategories = new EntitySet<DimProductSubcategory>(new Action<DimProductSubcategory>(this.attach_DimProductSubcategories), new Action<DimProductSubcategory>(this.detach_DimProductSubcategories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategoryKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductCategoryKey
		{
			get
			{
				return this._ProductCategoryKey;
			}
			set
			{
				if ((this._ProductCategoryKey != value))
				{
					this.OnProductCategoryKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductCategoryKey = value;
					this.SendPropertyChanged("ProductCategoryKey");
					this.OnProductCategoryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategoryAlternateKey", DbType="Int")]
		public System.Nullable<int> ProductCategoryAlternateKey
		{
			get
			{
				return this._ProductCategoryAlternateKey;
			}
			set
			{
				if ((this._ProductCategoryAlternateKey != value))
				{
					this.OnProductCategoryAlternateKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductCategoryAlternateKey = value;
					this.SendPropertyChanged("ProductCategoryAlternateKey");
					this.OnProductCategoryAlternateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnglishProductCategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EnglishProductCategoryName
		{
			get
			{
				return this._EnglishProductCategoryName;
			}
			set
			{
				if ((this._EnglishProductCategoryName != value))
				{
					this.OnEnglishProductCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._EnglishProductCategoryName = value;
					this.SendPropertyChanged("EnglishProductCategoryName");
					this.OnEnglishProductCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpanishProductCategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SpanishProductCategoryName
		{
			get
			{
				return this._SpanishProductCategoryName;
			}
			set
			{
				if ((this._SpanishProductCategoryName != value))
				{
					this.OnSpanishProductCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._SpanishProductCategoryName = value;
					this.SendPropertyChanged("SpanishProductCategoryName");
					this.OnSpanishProductCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrenchProductCategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FrenchProductCategoryName
		{
			get
			{
				return this._FrenchProductCategoryName;
			}
			set
			{
				if ((this._FrenchProductCategoryName != value))
				{
					this.OnFrenchProductCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._FrenchProductCategoryName = value;
					this.SendPropertyChanged("FrenchProductCategoryName");
					this.OnFrenchProductCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DimProductCategory_DimProductSubcategory", Storage="_DimProductSubcategories", ThisKey="ProductCategoryKey", OtherKey="ProductCategoryKey")]
		public EntitySet<DimProductSubcategory> DimProductSubcategories
		{
			get
			{
				return this._DimProductSubcategories;
			}
			set
			{
				this._DimProductSubcategories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DimProductSubcategories(DimProductSubcategory entity)
		{
			this.SendPropertyChanging();
			entity.DimProductCategory = this;
		}
		
		private void detach_DimProductSubcategories(DimProductSubcategory entity)
		{
			this.SendPropertyChanging();
			entity.DimProductCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimProductSubcategory")]
	public partial class DimProductSubcategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductSubcategoryKey;
		
		private System.Nullable<int> _ProductSubcategoryAlternateKey;
		
		private string _EnglishProductSubcategoryName;
		
		private string _SpanishProductSubcategoryName;
		
		private string _FrenchProductSubcategoryName;
		
		private System.Nullable<int> _ProductCategoryKey;
		
		private EntitySet<DimProduct> _DimProducts;
		
		private EntityRef<DimProductCategory> _DimProductCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductSubcategoryKeyChanging(int value);
    partial void OnProductSubcategoryKeyChanged();
    partial void OnProductSubcategoryAlternateKeyChanging(System.Nullable<int> value);
    partial void OnProductSubcategoryAlternateKeyChanged();
    partial void OnEnglishProductSubcategoryNameChanging(string value);
    partial void OnEnglishProductSubcategoryNameChanged();
    partial void OnSpanishProductSubcategoryNameChanging(string value);
    partial void OnSpanishProductSubcategoryNameChanged();
    partial void OnFrenchProductSubcategoryNameChanging(string value);
    partial void OnFrenchProductSubcategoryNameChanged();
    partial void OnProductCategoryKeyChanging(System.Nullable<int> value);
    partial void OnProductCategoryKeyChanged();
    #endregion
		
		public DimProductSubcategory()
		{
			this._DimProducts = new EntitySet<DimProduct>(new Action<DimProduct>(this.attach_DimProducts), new Action<DimProduct>(this.detach_DimProducts));
			this._DimProductCategory = default(EntityRef<DimProductCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSubcategoryKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductSubcategoryKey
		{
			get
			{
				return this._ProductSubcategoryKey;
			}
			set
			{
				if ((this._ProductSubcategoryKey != value))
				{
					this.OnProductSubcategoryKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductSubcategoryKey = value;
					this.SendPropertyChanged("ProductSubcategoryKey");
					this.OnProductSubcategoryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSubcategoryAlternateKey", DbType="Int")]
		public System.Nullable<int> ProductSubcategoryAlternateKey
		{
			get
			{
				return this._ProductSubcategoryAlternateKey;
			}
			set
			{
				if ((this._ProductSubcategoryAlternateKey != value))
				{
					this.OnProductSubcategoryAlternateKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductSubcategoryAlternateKey = value;
					this.SendPropertyChanged("ProductSubcategoryAlternateKey");
					this.OnProductSubcategoryAlternateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnglishProductSubcategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EnglishProductSubcategoryName
		{
			get
			{
				return this._EnglishProductSubcategoryName;
			}
			set
			{
				if ((this._EnglishProductSubcategoryName != value))
				{
					this.OnEnglishProductSubcategoryNameChanging(value);
					this.SendPropertyChanging();
					this._EnglishProductSubcategoryName = value;
					this.SendPropertyChanged("EnglishProductSubcategoryName");
					this.OnEnglishProductSubcategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpanishProductSubcategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SpanishProductSubcategoryName
		{
			get
			{
				return this._SpanishProductSubcategoryName;
			}
			set
			{
				if ((this._SpanishProductSubcategoryName != value))
				{
					this.OnSpanishProductSubcategoryNameChanging(value);
					this.SendPropertyChanging();
					this._SpanishProductSubcategoryName = value;
					this.SendPropertyChanged("SpanishProductSubcategoryName");
					this.OnSpanishProductSubcategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrenchProductSubcategoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FrenchProductSubcategoryName
		{
			get
			{
				return this._FrenchProductSubcategoryName;
			}
			set
			{
				if ((this._FrenchProductSubcategoryName != value))
				{
					this.OnFrenchProductSubcategoryNameChanging(value);
					this.SendPropertyChanging();
					this._FrenchProductSubcategoryName = value;
					this.SendPropertyChanged("FrenchProductSubcategoryName");
					this.OnFrenchProductSubcategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategoryKey", DbType="Int")]
		public System.Nullable<int> ProductCategoryKey
		{
			get
			{
				return this._ProductCategoryKey;
			}
			set
			{
				if ((this._ProductCategoryKey != value))
				{
					if (this._DimProductCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductCategoryKeyChanging(value);
					this.SendPropertyChanging();
					this._ProductCategoryKey = value;
					this.SendPropertyChanged("ProductCategoryKey");
					this.OnProductCategoryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DimProductSubcategory_DimProduct", Storage="_DimProducts", ThisKey="ProductSubcategoryKey", OtherKey="ProductSubcategoryKey")]
		public EntitySet<DimProduct> DimProducts
		{
			get
			{
				return this._DimProducts;
			}
			set
			{
				this._DimProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DimProductCategory_DimProductSubcategory", Storage="_DimProductCategory", ThisKey="ProductCategoryKey", OtherKey="ProductCategoryKey", IsForeignKey=true)]
		public DimProductCategory DimProductCategory
		{
			get
			{
				return this._DimProductCategory.Entity;
			}
			set
			{
				DimProductCategory previousValue = this._DimProductCategory.Entity;
				if (((previousValue != value) 
							|| (this._DimProductCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DimProductCategory.Entity = null;
						previousValue.DimProductSubcategories.Remove(this);
					}
					this._DimProductCategory.Entity = value;
					if ((value != null))
					{
						value.DimProductSubcategories.Add(this);
						this._ProductCategoryKey = value.ProductCategoryKey;
					}
					else
					{
						this._ProductCategoryKey = default(Nullable<int>);
					}
					this.SendPropertyChanged("DimProductCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DimProducts(DimProduct entity)
		{
			this.SendPropertyChanging();
			entity.DimProductSubcategory = this;
		}
		
		private void detach_DimProducts(DimProduct entity)
		{
			this.SendPropertyChanging();
			entity.DimProductSubcategory = null;
		}
	}
}
#pragma warning restore 1591
