//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactResellerSales
    {
        public int ProductKey { get; set; }
        public int OrderDateKey { get; set; }
        public int DueDateKey { get; set; }
        public int ShipDateKey { get; set; }
        public int ResellerKey { get; set; }
        public int EmployeeKey { get; set; }
        public int PromotionKey { get; set; }
        public int CurrencyKey { get; set; }
        public int SalesTerritoryKey { get; set; }
        public string SalesOrderNumber { get; set; }
        public byte SalesOrderLineNumber { get; set; }
        public Nullable<byte> RevisionNumber { get; set; }
        public Nullable<short> OrderQuantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ExtendedAmount { get; set; }
        public Nullable<double> UnitPriceDiscountPct { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<decimal> ProductStandardCost { get; set; }
        public Nullable<decimal> TotalProductCost { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string CarrierTrackingNumber { get; set; }
        public string CustomerPONumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
    
        public virtual DimCurrency DimCurrency { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual DimEmployee DimEmployee { get; set; }
        public virtual DimProduct DimProduct { get; set; }
        public virtual DimPromotion DimPromotion { get; set; }
        public virtual DimReseller DimReseller { get; set; }
        public virtual DimSalesTerritory DimSalesTerritory { get; set; }
    }
}
