//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDMPrep
    {
        public string EnglishProductCategoryName { get; set; }
        public string Model { get; set; }
        public int CustomerKey { get; set; }
        public string Region { get; set; }
        public Nullable<int> Age { get; set; }
        public string IncomeGroup { get; set; }
        public short CalendarYear { get; set; }
        public short FiscalYear { get; set; }
        public byte Month { get; set; }
        public string OrderNumber { get; set; }
        public byte LineNumber { get; set; }
        public short Quantity { get; set; }
        public decimal Amount { get; set; }
    }
}
