//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTimeSeries
    {
        public string ModelRegion { get; set; }
        public Nullable<int> TimeIndex { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public short CalendarYear { get; set; }
        public byte Month { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
    }
}
